### ISSUE TITLE
[BUG] Spark Connect not detected on Databricks

### ISSUE THREAD

**Issue by YevIgn** [Nike-Inc/koheesio#102]
## Describe the bug
When running on Databricks in Spark Connect mode (for example Shared Isolation mode, Job Cluster, DBR 15.4) - Spark Connect isn't detected by koheesio, which leads to exceptions in code that can only be executed on regular `SparkSession`.

## Steps to Reproduce
Run code that involves for example use of `DeltaTableWriter` with `merge_builder` passed as `DeltaMergeBuilder`, it will fail on 0.9.0rc versions.

## Expected behavior
Spark Connect is detected while using Koheesio 0.9.0 (future release branch).

## Environment
- DBR 15.4
- Koheesio 0.9.0rc2

## Additional context
The issue is caused by relying on non-existing configuration parameter `spark.remote` - https://github.com/Nike-Inc/koheesio/blob/abb435b409b620ae71dd868a5647256eeb4194b4/src/koheesio/spark/utils/connect.py#L17

**Comment by dannymeijer** [comment]
we could take inspiration from Spark 4.0 pre-release - it's unfortunate that this util is not available in earlier spark versions
https://spark.apache.org/docs/4.0.0-preview1/api/python/_modules/pyspark/sql/utils.html#is_remote

```python
def is_remote() -> bool:
    """
    Returns if the current running environment is for Spark Connect.

    .. versionadded:: 4.0.0

    Notes
    -----
    This will only return ``True`` if there is a remote session running.
    Otherwise, it returns ``False``.

    This API is unstable, and for developers.

    Returns
    -------
    bool

    Examples
    --------
    >>> from pyspark.sql import is_remote
    >>> is_remote()
    False
    """
    return ("SPARK_CONNECT_MODE_ENABLED" in os.environ) or is_remote_only()
```

**Comment by YevIgn** [comment]
Neither of this options is set on Databricks Runtime :/ 

But also there is another bug to be fixed, after manually setting `spark.remote` the code continues to execute, but fails due to non-replaced `isinstance(writer, DeltaMergeBuilder)` check further on.

There are couple of them actually:
* https://github.com/Nike-Inc/koheesio/blob/abb435b409b620ae71dd868a5647256eeb4194b4/src/koheesio/spark/writers/delta/batch.py#L251
* https://github.com/Nike-Inc/koheesio/blob/abb435b409b620ae71dd868a5647256eeb4194b4/src/koheesio/spark/writers/delta/batch.py#L326
* https://github.com/Nike-Inc/koheesio/blob/abb435b409b620ae71dd868a5647256eeb4194b4/src/koheesio/spark/writers/delta/batch.py#L381

Given proliferation of this check in several places, it makes sense to make only once at instance initialisation or spin a separate class.

**Comment by YevIgn** [comment]
Validated on 0.9.0rc6, now Spark Connect session is correctly detected.
