### ISSUE TITLE
[FEATURE] Exists function in DeltaTableStep should not log error

### ISSUE THREAD

**Issue by menathan** [Nike-Inc/koheesio#34]
## Is your feature request related to a problem? Please describe.

https://github.com/Nike-Inc/koheesio/blob/90e48fc0729973e22d459c4a575d4f649ae7ccd4/src/koheesio/spark/delta.py#L307

Exist function should not be biased when it comes to evaluating whether it is good or bad for a table to exist.

## Describe the solution you'd like

Few possible suggestions:

- change to warning or info
- keep error, but check that if self.create_if_not_exists is false, then do log as an error.

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by pariksheet** [comment]
Assign it to Federica

**Comment by dannymeijer** [comment]
Fixed with #70
