### ISSUE TITLE
[BUG] Step get attribute is passing on missed attributes and shadow excpetions

### ISSUE THREAD

**Issue by mikita-sakalouski** [Nike-Inc/koheesio#81]
## Describe the bug
The `__getattr__` method in the `Step` class was returning `None` when trying to access unavailable attributes in child classes. Additionally, it was shadowing exceptions that should have been raised.

## Steps to Reproduce
1. Create a child class inheriting from `Step`.
2. Attempt to access an unavailable attribute in the child class.
3. Observe that `None` is returned instead of an exception being raised.

## Expected behavior
An `AttributeError` should be raised when trying to access an unavailable attribute in the `Step` child classes.

**Comment by dannymeijer** [comment]
Fixed in #82 - will be part of upcoming 0.9 release
