### ISSUE TITLE
[FEATURE] Add box functionality

### ISSUE THREAD

**Issue by ToneVDB** [Nike-Inc/koheesio#89]
## Is your feature request related to a problem? Please describe.

Missing functionality on the Box class, Both overwrite and delete is missing.

## Describe the solution you'd like

I would like an `overwrite:bool` flag on `BoxFileWriter` so you can overwrite the file on Box if it already exists.
I would like a `BoxFileDeleter` so I can delete files on box.

## Describe alternatives you've considered

This is basic functionality, there should not be a workaround needed for this.

## Additional context

See following links:
https://github.com/box/box-python-sdk/blob/main/docs/usage/files.md#move-a-file
https://github.com/box/box-python-sdk/blob/main/docs/usage/files.md#delete-a-file

**Comment by dannymeijer** [comment]
alternatively, we could also do a write_mode, like what we have in SFTP. For reference: https://github.com/Nike-Inc/koheesio/blob/485ee90f9f624897d27800ecc0510df35a2cb707/src/koheesio/integrations/spark/sftp.py#L149-L152
